### PR TITLE
Replace Travis with GitHub CI

### PR DESCRIPTION
**Pull request by UsamaSadiq**
**Issue:** [BOM-2987](https://openedx.atlassian.net/browse/BOM-2987)

### Description
- Replaced `Travis` with `GitHub CI`.

### CODE REVIEW

**Comment by jolyonb** [comment]
Surprised to see this - this repo went radio silent for a long time! Glad it's still in use.

**Comment by jinder1s** [comment]
Hi, this repository is breaking repo-health checks cause of the way .travis.yml is formatting. I'd like to see this PR go through and delete the .travis.yml file. Let me know if I can help in any way.

**Comment by jolyonb** [comment]
No issues from me.

**Comment by UsamaSadiq** [comment]
@jolyonb could you please merge this PR? I don't have access to merge this.

**Comment by jinder1s** [comment]
@UsamaSadiq Could you remove the .travis.yml file as well? Or do you plan on doing that in a future PR?

**Comment by UsamaSadiq** [comment]
@jinder1s removed `travis.yml` file too.

**Comment by jolyonb** [comment]
I don't have merge privileges here. I own the original repository that this was forked from, but this repository belongs to edX.

**Comment by UsamaSadiq** [comment]
@jmbowman would you have access to merge this PR?

**Pull request merged**
